### ISSUE TITLE
What is an example of what callback should be?

### ISSUE THREAD

**Issue by EasyAsABC123** [true-dubach/node-twitch-webhook#12]
Is it suppose to point to the `listen` config?

```
listen: {
          port: 5000,           // default: 8443
          host: '127.0.0.1',    // default: 0.0.0.0
          autoStart: true       // default: true
      }
```

or should i be adding a route that points to a function?

or should it point to the callback for the auth? `http://localhost:5000/auth/twitch/callback`?

**Comment by JavaCrow** [comment]
Hi, first sorry for my english ^^'

I don't know if that can help you but a common config (local) for that module is:

```javascript 
this.twitchWebhook = new TwitchWebhook({
            client_id: 'YourClientId', //Get from twitch developers
            callback: 'http://0.0.0.0:8443/', //This is your public IP, Be sure of turn-on port-forwarding in your  router to port 8443
            secret: 'YourSecret', //Get from twitch developers default: false
            lease_seconds: 259200,    // default: 864000 (maximum value)
            listen: {
                port: 8443,           // default: 8443
                host: '192.168.1.111',    // <--- Thats is your private IP default: 0.0.0.0
                autoStart: true      // default: true
            }
        });
```

So the **callback** should be the IP where Twitch can send events.

**Comment by nic11** [comment]
Yes, @CrowDevelop is right. `listen` points to the IP address and port where we will listen to incoming connections, while `callback` should be the URL where Twitch can send events. The important thing to note here, that these two parameters are actually quite different.

## Port forwarding and some notes

For example, if you want to run this on your home PC, you should keep in mind that IP address system shows you (e.g. `192.168.1.111`) is inside your home network created by router and can't be reached from the Internet. Moreover, huge amount of computers in the world have local IP `192.168.1.111` right now. In this case you should do some [port forwarding](https://en.wikipedia.org/wiki/Port_forwarding)  (Google for something like "\<your router manufacturer\> port forwarding" to get a guide) and set `callback` to something like `http://11.22.33.44:5151` where `11.22.33.44` is your [public IP](https://whatismyipaddress.com/) and `5151` is any port that your router and ISP allow to expose. Note that your public and private ports may differ just like your public and private IP addresses. For example you can forward port `5151` to `192.168.1.111:8080` (if you have `listen.port = 8080`).

As for `listen.host` parameter, it allows you to specify the IP address which will be listened for incoming connections. `0.0.0.0` will make program to accept incoming connections to any IP, including `127.0.0.1` and `192.168.1.111`, while `192.168.1.111` will not respond to connections from `127.0.0.1` (`localhost`), so you won't be able to reach your app using `http://localhost:8080`. You can read more [here](https://serverfault.com/questions/78048/whats-the-difference-between-ip-address-0-0-0-0-and-127-0-0-1).

## Reverse proxy

If you're using a reverse proxy, e.g. [nginx](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/), you'll also end up in having radically different `listen` and `callback` values.

Please note that it is important to have `listen.host` equal to `127.0.0.1` for security reasons, because `0.0.0.0` will make your backend exposed to the Internet, which is not what you want when you have a reverse proxy.

For example, your reverse proxy could be configured to proxy requests to `https://api.example.com/callbacks/twitch/<path>` to `http://127.0.0.1:8080/<path>`. In this case you want to use `https://api.example.com/callbacks/twitch` as `callback`, `127.0.0.1` as `listen.host` and `8080` as your `listen.port`.

## Using Node.js built-in https server

Though not recommended, one can use Node's built-in HTTPS server instead of a reverse proxy. As stated in docs:

    * @param {boolean|Object} [options.https=false] - Should use https connection.
    * If yes, these options to be passed to `https.createServer()`.

`node-twitch-webhook` will create HTTPS server using [`https.createServer`](https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener) instead of HTTP server if `https` parameter specified.
