### ISSUE TITLE
Access to unknown URL/method

### ISSUE THREAD

**Issue by Knoot** [true-dubach/node-twitch-webhook#19]
stops working after 1h - 1h 30m
` / twitch-webhooks WARNING Access to unknown URL/method attempted: GET /`
After receiving this message in the console, listening no longer works.
This only happens on the remote server, with local tests everything is fine. Remote Ubuntu Server 20.04 64bit if it matters.
I suspect this is due to ngrok, but not sure about it. What can I do to find out the real reason for this?

node: 14.16.1
npm: 7.11.2

**Comment by Knoot** [comment]
`twitch-webhooks WARNING Access to unknown URL/method attempted: POST /_ignition/execute-solution`

**Comment by nic11** [comment]
I guess, that happened because Twitch updated API somehow, which made this library incompatible in some circumstances.

Unfortunately, we don't have enough time to keep maintaining this library. Maybe, some of the forks will help you. See this, for example: https://github.com/true-dubach/node-twitch-webhook/pull/15#issuecomment-695117924

Possible contacts: @JMTK, @TheCricket

**Comment by JMTK** [comment]
I haven't seen anything like that before. You're welcome to test my fork by adding this in your package.json:
```
"dependencies": {
...
    "twitch-webhook": "github:JMTK/node-twitch-webhook"
...
```
Did you update your ngrok version or node version recently?

**Comment by Knoot** [comment]
i updated node but that was before starting to work with this

**Comment by Knoot** [comment]
sorry i'm not sure how i got here but i'm having problems with twitch-webhooks, not twitch-webhook
